---
title: "Milestone 4"
author: "Liz Masten"
date: "2/27/2020"
output: bookdown::pdf_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(foreign)
library(tinytex)
library(gt)
library(bookdown)
library(stargazer)
library(tidyverse)
```

```{r}

data <- read.dta("fpy_replication_data_jop_2012.dta")

#This milestone needs to contain: 

#a bibliography (and associated references);
#a footnote, a table (using the gt package); and 
#a regression table (using whatever packages you like.

#All of this can be brief (i.e., just two entries in the References is fine) and fake (made up data in the tables).
```

Please see my GitHub for <a href = https://github.com/LizMas/ms_4 >this Milestone's repository</a>. 
Additionally, please see my GitHub for my <a href = https://github.com/LizMas/replication >final project's repository</a>. 

```{r}

#table using gt package 

table <- data %>% 
  filter(year >= 1990) %>% 
  select(year, terrorCounts) %>% 
  group_by(year) %>% 
  summarise(events = sum(terrorCounts))
  


gt_table <- gt(table) %>% 
            tab_header(title = "Title of Table")

gt_table

```


```{r}

#prep a quick regression for stargazer table example 

x <- data %>% 
  select(year, terrorCounts, rivalry) %>% 
  group_by(year) %>% 
  drop_na()

model_x <- glm(rivalry ~ terrorCounts, data = x)

```

```{r, results='asis'}

#To get stargazer to work with a pdf output, I had to put results = 'asis' in the code chunk. 

#Using the normal output method I used in the past gave me a gross looking table, so I changed it to header = FALSE and type = 'latex' to make it compatable with the pdf output, I suppose. 

stargazer(model_x, header=FALSE, type='latex')


```


Here is an example of how to footnote.^[footnote_1] 
And another one.^[footnote_2]
